/// <reference types="npm:@types/react@18.3.1" />
import * as React from 'npm:react@18.3.1'
import {
  Body, Container, Head, Heading, Html, Preview, Text, Section, Row, Column, Hr, Button,
} from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

const SITE_NAME = 'Compare Water Filters'

interface PaymentConfirmationProps {
  providerName?: string
  invoiceNumber?: string
  totalAmount?: string
  leadCount?: number
  periodStart?: string
  periodEnd?: string
  paidAt?: string
}

const PaymentConfirmationEmail = ({
  providerName = 'Provider',
  invoiceNumber = 'INV-000000',
  totalAmount = '$0',
  leadCount = 0,
  periodStart = '',
  periodEnd = '',
  paidAt = '',
}: PaymentConfirmationProps) => {
  const formatDate = (d: string) =>
    d ? new Date(d).toLocaleDateString('en-AU', { day: 'numeric', month: 'short', year: 'numeric' }) : ''

  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>Payment received for invoice {invoiceNumber} — {totalAmount}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={headerSection}>
            <Text style={headerIcon}>✅</Text>
            <Heading style={h1}>Payment Received</Heading>
            <Text style={headerSubtext}>
              Hi <strong>{providerName}</strong>, your payment has been successfully processed.
            </Text>
          </Section>

          <Hr style={divider} />

          <Section style={infoSection}>
            <Heading as="h3" style={sectionHeading}>Payment Details</Heading>
            <Row style={infoRow}><Column style={labelCol}>Invoice #</Column><Column style={valueCol}>{invoiceNumber}</Column></Row>
            <Row style={infoRow}><Column style={labelCol}>Amount Paid</Column><Column style={amountCol}>{totalAmount}</Column></Row>
            <Row style={infoRow}><Column style={labelCol}>Leads</Column><Column style={valueCol}>{leadCount} lead{leadCount !== 1 ? 's' : ''}</Column></Row>
            <Row style={infoRow}><Column style={labelCol}>Period</Column><Column style={valueCol}>{formatDate(periodStart)} – {formatDate(periodEnd)}</Column></Row>
            {paidAt && (
              <Row style={infoRow}><Column style={labelCol}>Paid on</Column><Column style={valueCol}>{formatDate(paidAt)}</Column></Row>
            )}
            <Row style={infoRow}><Column style={labelCol}>Status</Column><Column style={valueCol}>
              <span style={statusPaid}>Paid</span>
            </Column></Row>
          </Section>

          <Hr style={divider} />

          <Text style={bodyText}>
            Thank you for your prompt payment. Your account is in good standing and you'll continue receiving leads as normal.
          </Text>

          <Text style={bodyText}>
            You can view your full billing history and download invoices from your vendor dashboard.
          </Text>

          <Section style={{ textAlign: 'center' as const, margin: '24px 0 0' }}>
            <Button style={ctaButton} href="https://comparewaterfilters.lovable.app/vendor/billing">
              View Billing Dashboard
            </Button>
          </Section>

          <Hr style={divider} />

          <Text style={footer}>
            This receipt was generated by {SITE_NAME}
          </Text>
        </Container>
      </Body>
    </Html>
  )
}

export const template = {
  component: PaymentConfirmationEmail,
  subject: (data: Record<string, any>) =>
    `Payment received: Invoice ${data.invoiceNumber || ''} — ${data.totalAmount || ''}`,
  displayName: 'Payment confirmation',
  previewData: {
    providerName: 'Pure Water Solutions',
    invoiceNumber: 'INV-ABC123',
    totalAmount: '$86',
    leadCount: 2,
    periodStart: '2026-03-01',
    periodEnd: '2026-03-31',
    paidAt: '2026-04-06',
  },
} satisfies TemplateEntry

const main = { backgroundColor: '#ffffff', fontFamily: "'Plus Jakarta Sans', Arial, sans-serif" }
const container = { padding: '24px 28px', maxWidth: '540px' }
const headerSection = { textAlign: 'center' as const, padding: '16px 0 8px' }
const headerIcon = { fontSize: '32px', margin: '0 0 8px' }
const h1 = { fontSize: '22px', fontWeight: 'bold' as const, color: 'hsl(220, 20%, 14%)', margin: '0 0 8px' }
const headerSubtext = { fontSize: '14px', color: 'hsl(220, 10%, 46%)', margin: '0' }
const divider = { borderColor: '#e5e2dc', margin: '20px 0' }
const infoSection = { margin: '0' }
const sectionHeading = { fontSize: '13px', fontWeight: '600' as const, color: 'hsl(168, 42%, 40%)', margin: '0 0 10px', textTransform: 'uppercase' as const, letterSpacing: '0.5px' }
const infoRow = { margin: '0 0 6px' }
const labelCol = { fontSize: '13px', color: 'hsl(220, 10%, 46%)', width: '120px', verticalAlign: 'top' as const, padding: '2px 0' }
const valueCol = { fontSize: '13px', color: 'hsl(220, 20%, 14%)', fontWeight: '500' as const, padding: '2px 0' }
const amountCol = { fontSize: '16px', color: 'hsl(220, 20%, 14%)', fontWeight: '700' as const, padding: '2px 0' }
const statusPaid: React.CSSProperties = { backgroundColor: 'hsl(142, 40%, 92%)', color: 'hsl(142, 50%, 28%)', padding: '2px 10px', borderRadius: '12px', fontSize: '12px', fontWeight: 500 }
const bodyText = { fontSize: '14px', color: 'hsl(220, 10%, 46%)', lineHeight: '1.6', margin: '0 0 12px' }
const footer = { fontSize: '12px', color: '#999999', margin: '0', textAlign: 'center' as const }
const ctaButton = { backgroundColor: 'hsl(168, 42%, 40%)', color: '#ffffff', fontSize: '14px', fontWeight: '600' as const, borderRadius: '12px', padding: '12px 28px', textDecoration: 'none' }
